const { Router } = require("express");
const deptRoutes = require("./deptRoutes");
const roleRoutes = require("./roleRoutes");
const userRoutes = require("./userRoutes");
const unitRoutes = require("./unitRoutes");
const partyRoutes = require("./partyRoutes");
const groupRoutes = require("./groupRoutes");
const salaryRoutes = require("./salaryRoutes");
const clientRoutes = require("./clientRoutes");
const productRoutes = require("./productRoutes");
const currencyRoutes = require("./currencyRoutes");
const settingsRoutes = require("./settingsRoutes");
const categoryRoutes = require("./categoryRoutes");
const warehouseRoutes = require("./warehouseRoutes");
const balanceHistory = require("./balanceHistoryRoutes");
const translationRoutes = require("./translationRoutes");
const satisfactionRoutes = require("./satisfactionRoutes");
const productCategory = require("./productCategoryRoutes");
const saledProductRoutes = require("./saledProductRoutes");
const transferHistoryRoutes = require("./transferHisrtoryRoues");
const satisfactionTypeRoutes = require("./satisfactionTypeRoutes");

const router = Router();

router.use("/roles", roleRoutes);
router.use("/users", userRoutes);
router.use("/depts", deptRoutes);
router.use("/units", unitRoutes);
router.use("/groups", groupRoutes);
router.use("/parties", partyRoutes);
router.use("/salary", salaryRoutes);
router.use("/clients", clientRoutes);
router.use("/products", productRoutes);
router.use("/balance", balanceHistory);
router.use("/currency", currencyRoutes);
router.use("/settings", settingsRoutes);
router.use("/categories", categoryRoutes);
router.use("/warehouses", warehouseRoutes);
router.use("/translations", translationRoutes);
router.use("/satisfactions", satisfactionRoutes);
router.use("/saled-products", saledProductRoutes);
router.use("/product-categories", productCategory);
router.use("/transfer-history", transferHistoryRoutes);
router.use("/satisfaction-type", satisfactionTypeRoutes);

module.exports = router;
